name: biggerthanme
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001f34'
    - '#596c73'
    - '#fdbe00'
    - '#b98800'
    - '#48acb4'
  brandStrength: 0.9522478361614048
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
